#!/usr/bin/env python3
"""Mechanically ports the legacy sigmac-config.yml OSSEM field mappings to a
pySigma processing pipeline YAML for pySigma-backend-elasticsearch.

Dev-time tool, not run inside the container - its output
(../pipeline/helk_ossem_pipeline.yml) is committed and used as-is at runtime.
Re-run manually only if legacy-sigmac-config.yml changes.

Scope: simple 1:1 field renames port directly. EventID-conditional dict
entries (e.g. SubjectUserName varies by EventID) are collapsed to a single
majority target value rather than reproduced with full per-EventID fidelity -
see MODERNIZATION.md Phase 2 notes. Fields with no safe majority mapping are
left unmapped (original Sigma field name passes through unchanged).
"""
import os
from collections import Counter

import yaml

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "..", "..", "helk-sigma-convert", "legacy-sigmac-config.yml")
DST = os.path.join(HERE, "..", "pipeline", "helk_ossem_pipeline.yml")

with open(SRC) as f:
    cfg = yaml.safe_load(f)

mapping = {}
collapsed = []
skipped = []

for field, target in cfg["fieldmappings"].items():
    if isinstance(target, str):
        if target != field:
            mapping[field] = target
        continue

    values = [v for k, v in target.items() if k != "default"]
    default = target.get("default")
    if not values:
        if default and default != field:
            mapping[field] = default
        continue

    counts = Counter(values)
    dominant_value, dominant_count = counts.most_common(1)[0]
    is_majority = dominant_count > len(values) / 2

    if is_majority and dominant_value != field:
        mapping[field] = dominant_value
        if len(counts) > 1 or (default and default != dominant_value):
            collapsed.append((field, dominant_value, dict(target)))
    elif default and default != field:
        mapping[field] = default
        collapsed.append((field, default, dict(target)))
    else:
        skipped.append((field, dict(target)))

pipeline = {
    "name": "HELK OSSEM field mapping (ported from legacy sigmac-config.yml)",
    "priority": 20,
    "transformations": [
        {
            "id": "helk_ossem_field_mapping",
            "type": "field_name_mapping",
            "mapping": dict(sorted(mapping.items())),
        }
    ],
}

with open(DST, "w") as f:
    f.write(
        "# Generated by generate_pipeline.py from legacy-sigmac-config.yml - do not\n"
        "# hand-edit; re-run the generator instead. See its module docstring for scope.\n"
    )
    yaml.dump(pipeline, f, sort_keys=False, default_flow_style=False, width=100)

print(f"Mapped {len(mapping)} fields directly.")
print(f"\nCollapsed {len(collapsed)} EventID-conditional fields to a single dominant value:")
for field, value, original in collapsed:
    print(f"  {field} -> {value}  (was: {original})")
print(f"\nSkipped {len(skipped)} fields with no safe majority mapping (left unmapped):")
for field, original in skipped:
    print(f"  {field}  (was: {original})")
